src/TeamUtils.LeadTimeTrackingHelper/Models/ActivityModel.cs
using System.ComponentModel.DataAnnotations;
using TeamUtils.LeadTimeTrackingHelper.Domain.Data;

namespace TeamUtils.LeadTimeTrackingHelper.Models
{
    public class ActivityModel:Activity
    {
        [Required]
        public new string Key { get; set; }

        public bool IsNew { get; set; }
    }
}

src/TeamUtils.LeadTimeTrackingHelper/Models/ChangeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TeamUtils.LeadTimeTrackingHelper.Models.Validation;

namespace TeamUtils.LeadTimeTrackingHelper.Models
{
    public class ChangeModel
    {
        [Required]
        public string Activity { get; set; }

        [Required]
        public string From { get; set; }

        [Required, NotMatch("From")]
        public string To { get; set; }

        [Timestamp]
        public string Timestamp { get; set; }
    }
}

src/TeamUtils.LeadTimeTrackingHelper/Models/TrackChangeRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using TeamUtils.LeadTimeTrackingHelper.Models.Validation;

namespace TeamUtils.LeadTimeTrackingHelper.Models
{
    public class TrackChangeRequest
    {
        [Required]
        public string Activity { get; set; }

        [Required]
        public string From { get; set; }

        [Required, NotMatch("From")]
        public string To { get; set; }

        [Timestamp]
        public string Timestamp { get; set; }
    }
}

src/TeamUtils.LeadTimeTrackingHelper/Models/Validation/NotMatchAttribute.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TeamUtils.LeadTimeTrackingHelper.Models.Validation
{
    public class NotMatchAttribute:CompareAttribute
    {
        private readonly string _otherProperty;

        public NotMatchAttribute(string otherProperty):base(otherProperty)
        {
            _otherProperty = otherProperty;
            ErrorMessage = "{0} and {1} should not be equal";
        }

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            var result = base.IsValid(value, validationContext);
            if (result != ValidationResult.Success)
                return ValidationResult.Success;

            return new ValidationResult(FormatErrorMessage(_otherProperty));
        }
    }
}

src/TeamUtils.LeadTimeTrackingHelper/Controllers/ActivitiesController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeamUtils.LeadTimeTrackingHelper.Domain.Data;
using TeamUtils.LeadTimeTrackingHelper.Models;

namespace TeamUtils.LeadTimeTrackingHelper.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly Repository _repository;

        public ActivitiesController(Repository repository)
        {
            if (repository == null)
                throw new ArgumentNullException(nameof(repository));

            _repository = repository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_repository.GetActivities().Select(a => new ActivityModel { Key = a.Key }));
        }

        [HttpPost]
        public IActionResult Add(ActivityModel model)
        {
            if (ModelState.IsValid)
            {
                var activity = _repository.GetActivity(model.Key);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(ActivityModel model)
        {
            _repository.Remove(_repository.GetActivity(model.Key));
            return RedirectToAction("Index");
        }
    }
}

src/TeamUtils.LeadTimeTrackingHelper/Controllers/ChangesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using TeamUtils.LeadTimeTrackingHelper.Models;
using TeamUtils.LeadTimeTrackingHelper.Domain;
using System;


namespace TeamUtils.LeadTimeTrackingHelper.Controllers
{
    public class ChangesController : Controller
    {
        private readonly ChangeTracker _tracker;

        public ChangesController(ChangeTracker tracker)
        {
            if (tracker == null)
                throw new ArgumentNullException(nameof(tracker));

            _tracker = tracker;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var requests = _tracker.GetRecentChanges().Select(x => new ChangeModel
            {
                Activity = x.Activity.Key,
                From = x.From.Key,
                To = x.To.Key,
                Timestamp = x.Timestamp.ToString()
            }).ToList();
            return View(requests);
        }

        [HttpPost]
        public IActionResult Track(ChangeModel request)
        {
            if (ModelState.IsValid)
            {
                DateTime time;
                if (DateTime.TryParse(request.Timestamp, out time))
                {
                    _tracker.Track(request.Activity, request.From, request.To, time);
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("Timestamp", "Timestamp should represent valid date and time");
                }
            }

            return View(request);
        }
    }
}

src/TeamUtils.LeadTimeTrackingHelper/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TeamUtils.LeadTimeTrackingHelper.Controllers
{
    public class ReportController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/TeamUtils.LeadTimeTrackingHelper/Views/Activities/Index.cshtml
@using TeamUtils.LeadTimeTrackingHelper.Models
@model IEnumerable<ActivityModel>
@{
    Layout = "_Layout";
}

<h1>Activities</h1>
<div>
    @Html.Partial("Partials/_Activity", new ActivityModel { IsNew = true })
</div>
<div>
    <table>
        <thead>
            <tr>
                <td>Activitity</td>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Key</td>
                    <td>@Html.Partial("Partials/_DeleteActivity", item)</td>
                </tr>

            }
        </tbody>
    </table>
</div>

src/TeamUtils.LeadTimeTrackingHelper/Views/Activities/Partials/_Activity.cshtml
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@using TeamUtils.LeadTimeTrackingHelper.Models
@model ActivityModel

<h2>@(Model.IsNew ? "Add" : "Edit")</h2>

<form asp-controller="Activities" asp-action="Add">
    <input type="hidden" asp-for="IsNew" />
    <label asp-for="Key"></label><span>:</span>
    @if (Model.IsNew)
    {
        <input asp-for="Key"/><span asp-validation-for="Key"></span>
    }
    else
    {
        <input asp-for="Key" readonly="readonly"/>
    }
    <input type="submit" value="Submit"/>
</form>

src/TeamUtils.LeadTimeTrackingHelper/Views/Activities/Partials/_DeleteActivity.cshtml
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@using TeamUtils.LeadTimeTrackingHelper.Models
@model ActivityModel


<form asp-controller="Activities" asp-action="Delete">
    <input asp-for="Key" type="hidden" />
    <input type="submit" value="Delete"/>
</form>

src/TeamUtils.LeadTimeTrackingHelper/Views/Changes/Index.cshtml
@using TeamUtils.LeadTimeTrackingHelper.Models
@model IEnumerable<ChangeModel>
@{ 
    Layout = "_Layout";
}
<h1>Changes</h1>
<div>
    @Html.Partial("Partials/_Change",new ChangeModel())
</div>
<div>
    <h2>Recent changes</h2>
    <table>
        <thead>
            <tr>
                <td>Activity</td>
                <td>From</td>
                <td>To</td>
                <td>Timestamp</td>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Activity</td>
                    <td>@item.From</td>
                    <td>@item.To</td>
                    <td>@item.Timestamp</td>
                </tr>
            }
        </tbody>
    </table>
</div>

src/TeamUtils.LeadTimeTrackingHelper/Views/Changes/Partials/_Change.cshtml
@using TeamUtils.LeadTimeTrackingHelper.Models
@model ChangeModel
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"

<h2>Track one</h2>
<form aps-controller="Changes" asp-action="Track">
    <label asp-for="Activity"></label><span>:</span><input asp-for="Activity" /><span asp-validation-for="Activity"></span><br/>
    <label asp-for="From"></label><span>:</span><input asp-for="From" /><span asp-validation-for="From"></span><br />
    <label asp-for="To"></label><span>:</span><input asp-for="To" /><span asp-validation-for="To"></span><br />
    <label asp-for="Timestamp"></label><span>:</span><input asp-for="Timestamp" /><span asp-validation-for="Timestamp"></span><br />
    <input type="submit" value="Track"/>
</form>

src/TeamUtils.LeadTimeTrackingHelper/Views/Changes/Partials/_TrackChange.cshtml
@using TeamUtils.LeadTimeTrackingHelper.Models
@model TrackChangeRequest
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"

<h2>Track one</h2>
<form aps-controller="Changes" asp-action="Track">
    <label asp-for="Activity"></label><span>:</span><input asp-for="Activity" /><span asp-validation-for="Activity"></span><br/>
    <label asp-for="From"></label><span>:</span><input asp-for="From" /><span asp-validation-for="From"></span><br />
    <label asp-for="To"></label><span>:</span><input asp-for="To" /><span asp-validation-for="To"></span><br />
    <label asp-for="Timestamp"></label><span>:</span><input asp-for="Timestamp" /><span asp-validation-for="Timestamp"></span><br />
    <input type="submit" value="Track"/>
</form>

src/TeamUtils.LeadTimeTrackingHelper/Views/Changes/Track.cshtml
@using TeamUtils.LeadTimeTrackingHelper.Models
@model ChangeModel
@{
    Layout = "_Layout";
}

@Html.Partial("Partials/_Change", Model)

src/TeamUtils.LeadTimeTrackingHelper/Views/Report/Index.cshtml
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@{ 
    Layout = "_Layout";
}

<h1>Reports index page</h1>
<a asp-controller="Changes" asp-action="Index">Recent changes</a>
<a asp-controller="Activities" asp-action="Index">Activities</a>

src/TeamUtils.LeadTimeTrackingHelper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Lead Time Tracking Helper</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>